Server=172.31.33.63
# ServerActive=172.31.33.63
ListenPort=10150
PidFile=/run/zabbix/zabbix_agent2.pid
LogFile=/var/log/zabbix/zabbix_agent2.log
LogFileSize=100
BufferSend=10
BufferSize=500
Timeout=29
ControlSocket=/tmp/agent.sock
